export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';


// ESTO PORQUE el asincrono va a manejar 3 estados
export const REQUEST_ROBOTS_PENDING= 'REQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_SUCCESS= 'REQUEST_ROBOTS_SUCCESS';
export const REQUEST_ROBOTS_FAILED= 'REQUEST_ROBOTS_FAILED';